### ISSUE TITLE
Refactor for detectors, add detector (TSL2591 first)

### ISSUE THREAD

**Issue by yacobucci** [yacobucci/sensorkit#31]
Refactor:
- add internal db
- remove Store concept
- go through and ck error (not found) checking for all selectors
    - check not found
    - raise KeyError or whatever appropriate, derive a custom error
- replace devicetree with db tables
- add new config:
```
sensors:
  name:
    settings:
      - property: name
        value: val
    detector:
      interrupt:
        pin: num
        pull: up
        edge: falling
```

**Comment by yacobucci** [comment]
Probably need a selector to discriminate devices on MUX

```
sensors:
  name:
    selectors:
      channel: 0
    settings:
      - property: name
        value: val
    detector:
      interrupt:
        pin: num
        pull: up
        edge: falling
```
